export const card = [
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?photograph",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 0,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?neture",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 2,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?cat",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 3,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?dog",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 4,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?diwali",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 5,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?rangoli",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 6,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?gun",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 7,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?india",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 8,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?america",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 9,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?city",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 10,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?flawer",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 11,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?fruit",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 12,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?lion",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 13,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?tiger",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 14,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?fish",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 15,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?coding",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 16,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?bird",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 17,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?animals",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 18,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?machine",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 19,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?computer",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 20,
    },
    {
        title: 'Studay Material UI/UX design',
        line: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati nostrum dolor eligendi deleniti voluptates alias facere quas excepturi, nemo ipsam?",
        image: "https://source.unsplash.com/1600x900/?mobile",
        btn1: 'https://material.io/',
        btn2: 'https://github.com',
        id: 21,
    },
]